services:
  api:
    build:
      context: .
      dockerfile: src/Store.API/Dockerfile
    container_name: store-api
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ASPNETCORE_URLS: http://+:8080
    ports:
      - "8080:8080"
