services:
  api:
    build:
      context: .
      dockerfile: src/Store.API/Dockerfile
    container_name: store-api
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ASPNETCORE_URLS: http://+:8080
      ConnectionStrings__StoreDatabase: Host=postgres;Port=5432;Database=store;Username=store;Password=store
    ports:
      - "8080:8080"
    depends_on:
      - postgres

  postgres:
    image: postgres:16-alpine
    container_name: store-postgres
    environment:
      POSTGRES_DB: store
      POSTGRES_USER: store
      POSTGRES_PASSWORD: store
    ports:
      - "5432:5432"
    volumes:
      - store-postgres-data:/var/lib/postgresql/data

volumes:
  store-postgres-data:
